---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: deployer-role-binding
  namespace: hello-world
subjects:
  - kind: ServiceAccount
    name: aws-codebuild
roleRef:
  kind: Role
  name: deployer
  apiGroup: ""