---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: hello-world
    spec:
      containers:
        - name: hello-world
          image: gchinis/hello-world:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
