---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: deployer
  namespace: hello-world
rules:
  - apiGroups: [ "", "extensions" ]
    resources:
      - "deployments"
      - "pods"
    verbs: ["*"]